version: "3.9"
services:
  db:
    image: postgres:15
    container_name: nas_postgres
    restart: always
    environment:
      POSTGRES_USER: nasuser
      POSTGRES_PASSWORD: naspass
      POSTGRES_DB: raspberrycloud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: raspberrycloud-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: nasuser
      DB_PASS: naspass

volumes:
  postgres_data:
